// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCirlKwZlkucGZ61w22sX_hTgyMxc4eXMY',
    appId: '1:798584849294:web:e5a877a22494a7fe209adf',
    messagingSenderId: '798584849294',
    projectId: 'boutique-cafe-system',
    authDomain: 'boutique-cafe-system.firebaseapp.com',
    storageBucket: 'boutique-cafe-system.firebasestorage.app',
    measurementId: 'G-BCGRSKWT59',
  );

}